title: Soichiro Kumano (熊野 創一郎)
email: kumano0204@gmail.com
theme: jekyll-theme-cayman
author: Soichiro Kumano (熊野 創一郎)
languages: ['en', 'ja']
plugins:
  - jekyll-sitemap
sitemap:
  exclude:
    - '/google9fa1470a48e4e4d7.html'
