title: Soichiro Kumano (熊野 創一郎)
email: kumano0204@gmail.com
description: Soichiro Kumano's home page（熊野創一郎のホームページ）
theme: jekyll-theme-cayman
author: Soichiro Kumano (熊野 創一郎)
languages: ['en', 'ja']
plugins:
  - jekyll-sitemap
